// Package partner provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package partner

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// PetPayload defines model for PetPayload.
type PetPayload struct {
	// Availability Availability status expected by the partner (upper-case in the current client).
	Availability string `json:"availability"`

	// Labels Tag map; values are treated as strings.
	Labels *map[string]string `json:"labels,omitempty"`

	// Photos List of photo URLs.
	Photos []string `json:"photos"`

	// Reference String form of the local pet ID.
	Reference string `json:"reference"`

	// Title Display name of the pet.
	Title string `json:"title"`
}

// SyncResponse Generic success envelope (partner specific).
type SyncResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// SyncPetParams defines parameters for SyncPet.
type SyncPetParams struct {
	// IdempotencyKey Optional idempotency key used by the partner to deduplicate retries.
	// Reusing a key with a different payload is rejected.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// SyncPetJSONRequestBody defines body for SyncPet for application/json ContentType.
type SyncPetJSONRequestBody = PetPayload

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// PartnerAPIClient which conforms to the OpenAPI3 specification for this service.
type PartnerAPIClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*PartnerAPIClient) error

// Creates a new PartnerAPIClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*PartnerAPIClient, error) {
	// create a client with sane default values
	client := PartnerAPIClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *PartnerAPIClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *PartnerAPIClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SyncPetWithBody request with any body
	SyncPetWithBody(ctx context.Context, reference string, params *SyncPetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SyncPet(ctx context.Context, reference string, params *SyncPetParams, body SyncPetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *PartnerAPIClient) SyncPetWithBody(ctx context.Context, reference string, params *SyncPetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSyncPetRequestWithBody(c.Server, reference, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *PartnerAPIClient) SyncPet(ctx context.Context, reference string, params *SyncPetParams, body SyncPetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSyncPetRequest(c.Server, reference, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSyncPetRequest calls the generic SyncPet builder with application/json body
func NewSyncPetRequest(server string, reference string, params *SyncPetParams, body SyncPetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSyncPetRequestWithBody(server, reference, params, "application/json", bodyReader)
}

// NewSyncPetRequestWithBody generates requests for SyncPet with any type of body
func NewSyncPetRequestWithBody(server string, reference string, params *SyncPetParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reference", runtime.ParamLocationPath, reference)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, *params.IdempotencyKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

func (c *PartnerAPIClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *PartnerAPIClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SyncPetWithBodyWithResponse request with any body
	SyncPetWithBodyWithResponse(ctx context.Context, reference string, params *SyncPetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SyncPetResponse, error)

	SyncPetWithResponse(ctx context.Context, reference string, params *SyncPetParams, body SyncPetJSONRequestBody, reqEditors ...RequestEditorFn) (*SyncPetResponse, error)
}

type SyncPetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SyncResponse
	JSON409      *Error
	JSON4XX      *Error
	JSON5XX      *Error
}

// Status returns HTTPResponse.Status
func (r SyncPetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SyncPetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SyncPetWithBodyWithResponse request with arbitrary body returning *SyncPetResponse
func (c *ClientWithResponses) SyncPetWithBodyWithResponse(ctx context.Context, reference string, params *SyncPetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SyncPetResponse, error) {
	rsp, err := c.SyncPetWithBody(ctx, reference, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSyncPetResponse(rsp)
}

func (c *ClientWithResponses) SyncPetWithResponse(ctx context.Context, reference string, params *SyncPetParams, body SyncPetJSONRequestBody, reqEditors ...RequestEditorFn) (*SyncPetResponse, error) {
	rsp, err := c.SyncPet(ctx, reference, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSyncPetResponse(rsp)
}

// ParseSyncPetResponse parses an HTTP response from a SyncPetWithResponse call
func ParseSyncPetResponse(rsp *http.Response) (*SyncPetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SyncPetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SyncResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
